language: python
branches:
  only:
    - master
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=python
before_install:
    - docker build -t simplejava . 
script:
    - echo "Testing..." 
